### PR TITLE
Add streaming processing

### LINKED ISSUE #1: Streaming version
Hi there,

do you mind if I propose a PR which accepts a readableStream (and possibly works with Buffers rather than string conversion)?

Thanks :-)

### PR DESCRIPTION
**Pull request by oncletom**
closes #1

### CODE REVIEW

**Comment by ngryman** [comment]
Hey Tom,

Thanks alot for your PR! Good idea for removing `grunt` at the same time.

I'm ok with the idea of supporting streaming, but I don't feel comfortable that the streaming version doesn't share the same implementation of the *vanilla* one.
I think it would be possible doing something like:

```javascript
var readingTime = require('reading-time'),
    spy = require('through2');

var ReadingTimeStream = through2.ctor(function(chunk, encoding, callback) {
    var textChunk = chunk.toString();

    var stats = readingTime(textChunk);
    this.time += stats.time;
    this.words += stats.words;
        
    callback(null, chunk)
}, function(callback) {
    // XXX: I will probably expose `minutes` to avoid this computation
    this.text = Math.ceil(this.time / 60 / 1000 / 200) + ' min read';
    callback();
});

module.exports = function() {
    var stream = new ReadingTimeStream();
    stream.time = 0;
    stream.words = 0;
    return stream;
}
```

[through2-spy]: https://github.com/brycebaril/through2-spy

**Comment by oncletom** [comment]
What do you mean by *similar implementation*. Do you mean it is computed differently or the datastructure is different?

**Comment by ngryman** [comment]
I mean using the already existing `readingTime` function.

**Comment by oncletom** [comment]
Well I can but I won't for the sake of **not converting the buffer into a string**. The idea is to keep the input data unchanged (no binary to string conversion) and to be able to compute the length in multiple chunks rather than at once.

This is way more efficient in the case of a Webserver for example, as you can directly plug a chunked request object body Buffer object *without* spending time decoding it.

I therefore can't use your function as is, as you compare strings against strings. Which is fine. But we can avoid

At best, we can factorise the comparison code and maybe some of the iteration logic.

**Comment by ngryman** [comment]
> Well I can but I won't for the sake of not converting the buffer into a string.

`reading-time` is made to analyze a relatively small input (minutes-wize, which should be a maximum of `200 * 60 ~= 12000` words). The performance gain of not converting to a string should be negligible.

> to be able to compute the length in multiple chunks rather than at once.

The example I provided addresses this as it aggregates the statistics of every chunk.

> This is way more efficient in the case of a Webserver for example, as you can directly plug a chunked request object body Buffer object without spending time decoding it.

Still negligible for most use cases. If performance is truly crucial, any kind of cache would be a more adapted solution IMHO.

That said, if your needs involves high performance, you should perhaps publish your version as a standalone package which I will reference in my `readme`.

**Comment by oncletom** [comment]
I agree with all you say — this PR aims definitely at high performance (and the fun of playing with the Buffer "constraint"). Agreed best is maybe to publish it as a separate package.

Shall I propose the grunt-less commit as a separate PR and close this one?

Thanks for taking the time of the review and sharing your opinion about the proposal :+1:

**Comment by ngryman** [comment]
Yes sure, a grunt-less PR would be awesome!

After some thoughts on my side, I perhaps found a solution that could make us both happy ;)
I'll make a PR and would like your feedback.

**Pull request closed without merging**
